# Generated by Django 3.0.5 on 2022-02-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='Policy',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='PolicyRecord',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
